name: Testing with devbox

on:
  workflow_dispatch
    
jobs:
  devbox-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true

      - name: Run arbitrary commands
        run: devbox run -- pwsh -c "write-host 'Hello from pwsh' "

      - name: Run a script called powershell-host
        run: devbox run powershell-host

      - name: Run a script called powershell-test
        run: devbox run powershell-test  

      - name: Run a script called powershell-test
        run: devbox run env-list
           
